FeatureDefinitions:

  CheckLineFrequency:
    overwrite : False
    flow:
      - id: 0
        feature: SourceFile
      - id: 1
        function: spectrum
        args:
          meeg: id.0
          compute_psd_kwargs:
            method: 'welch'
            fmin: 0
            fmax: 200


  BasicPrep1:
    overwrite: False
    flow:
      - id: 0
        feature: SourceFile
      - id: 1
        function: basic_preprocessing
        args:
          mne_object: id.0
          resample: 250              # resample to 250 Hz
          notch_filter:
            freqs: [40]           # powerline
            filter_length: 'auto'
            notch_widths: null
            trans_bandwidth: 1
            method: 'fir'
            iir_params: null
            mt_bandwidth: null
            p_value: 0.05
            picks: null
            n_jobs: null
            phase: 'zero'
            fir_window: 'hamming'
            fir_design: 'firwin'
            pad: 'reflect_limited'
          filter_args:
            l_freq: 1.0
            h_freq: 40.0
          epoch_config:
            duration: 2.0
            overlap: 0.5
          extra_artifacts: True

  InterFeatureDependence:
    overwrite: False
    flow:
      - id: 0
        feature: BasicPrep1.fif
      - id: 1
        feature: CheckLineFrequency.nc
      - id: 3
        function: dummy
        args:
          param1: id.0
          param2: id.1
  
  SpectrumArrayWelch:
    overwrite: False
    flow:
      - id: 0
        feature: BasicPrep1.fif
      - id: 1
        function: spectrum_array
        args:
          meeg: id.0
          method: 'welch'
          method_kwargs:
            n_fft: 256
            n_overlap: 0
            n_per_seg: null
            average: 'mean'
            window: 'hamming'
            remove_dc: True
            output: 'power'
          extra_artifacts: True

  SpectrumArrayMultitaper:
    overwrite: False
    flow:
      - id: 0
        feature: BasicPrep1.fif
      - id: 1
        function: spectrum_array
        args:
          meeg: id.0
          method: 'multitaper'
          method_kwargs:
            bandwidth : null
            adaptive: False
            low_bias: True
            normalization: 'length'
            remove_dc: True
            output: 'power'
          extra_artifacts: True

  MEEGMetadata:
    overwrite: False
    flow:
      - id: 0
        feature: SourceFile
      - id: 1
        function: extract_meeg_metadata
        args:
          mne_object: id.0